source 'http://rubygems.org'

# Specify your gem's dependencies in eventq_rabbitmq.gemspec
gemspec

gem 'json', '1.8.3'
gem 'redlock'

platforms :ruby do
  gem 'openssl'
  gem 'oj', '2.15.0'
  gem 'pry'
end

platforms :jruby do
  gem 'pry-debugger-jruby'
  gem 'jruby-openssl'
end
