version: '2.1'

services:
  testrunner:
    build:
      context: ./
      dockerfile: Dockerfile
    image: eventq
    container_name: testrunner
    command: bash -c "./scripts/container_loop.sh"
    depends_on:
      - redis
      - rabbitmq
      - localstack
    volumes:
      - ./container_loop.sh:/scripts/container_loop.sh
      - ../:/src
    environment:
      - AWS_ACCESS_KEY_ID=mock_id
      - AWS_SECRET_ACCESS_KEY=mock_password
      - AWS_REGION=eu-west-1
      - AWS_SQS_ENDPOINT=http://localstack:4566
      - AWS_SNS_ENDPOINT=http://localstack:4566
#    env_file:
#      - ../.aws.env

  rabbitmq:
    image: rabbitmq:3.6.5
    container_name: rabbitmq

  redis:
    image: redis:alpine
    container_name: eventq_redis
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=sqs,sns
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
    ports:
      - "8085:8080"
      - "4566:4566"
