version: '2.1'

services:
  testrunner:
    build:
      context: ./
      dockerfile: Dockerfile
    image: eventq
    container_name: testrunner
    command: bash -c "./scripts/container_loop.sh"
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ./container_loop.sh:/scripts/container_loop.sh
      - ../:/src
    environment:
      - AWS_ACCESS_KEY_ID=mock_id
      - AWS_SECRET_ACCESS_KEY=mock_password
      - AWS_REGION=us-east-1
      - AWS_SQS_ENDPOINT=http://goaws:4100
      - AWS_SNS_ENDPOINT=http://goaws:4100
      # - AWS_SQS_ENDPOINT=http://localstack:4576
      # - AWS_SNS_ENDPOINT=http://localstack:4575
      # - AWS_SQS_ENDPOINT=http://sqs:9324
      # - AWS_SNS_ENDPOINT=http://sns:9911
#    env_file:
#      - ../.aws.env

  rabbitmq:
    image: rabbitmq:3.6.5
    container_name: rabbitmq

  redis:
    image: redis:alpine
    container_name: eventq_redis
    ports:
      - "6379:6379"

  # sns:
  #   image: s12v/sns
  #   ports:
  #   - "9911:9911"
  #   depends_on:
  #   - sqs
    # networks:
    #   default:
    #     aliases:
    #       - sns.dev.sageone.com

  # sqs:
  #   image: meteogroup/sqsmock
  #   ports:
  #   - "9324:9324"
  #   environment:
  #     ELASTICMQ_HOST: 'sqs'
    # - "9325:9325"
    # environment:
    #   NODE_HOST: "sqs.dev.sageone.com"
    # networks:
    #   default:
    #     aliases:
    #       - sqs.dev.sageone.com

  goaws:
    image: pafortin/goaws
    container_name: goaws
    ports:
      - "4100:4100"

  # localstack:
  #   image: localstack/localstack
  #   container_name: goaws
  #   environment:
  #     - SERVICES=sqs:4576,sns:4575
  #     - HOSTNAME=localstack
  #     - HOSTNAME_EXTERNAL=localstack
  #   ports:
  #     - "8085:8080"
  #     - "4576:4576"
  #     - "4575:4575"
