rabbitmq:
  image: gonkulatorlabs/rabbitmq
  container_name: rabbitmq

testrunner:
  image: eventq/rabbitmq
  container_name: testrunner
  command: bash -c "./scripts/container_loop.sh"
  links:
    - rabbitmq
    - redis
  volumes:
    - ./container_loop.sh:/scripts/container_loop.sh
    - ../.:/gem_src

testrunner2:
  image: 522104923602.dkr.ecr.eu-west-1.amazonaws.com/sageone/jruby:20170623
  container_name: testrunner_jruby
  command: bash -c "./scripts/container_loop.sh"
  links:
    - rabbitmq
    - redis
  volumes:
    - ./container_loop.sh:/scripts/container_loop.sh
    - ../.:/gem_src

redis:
  image: redis:alpine
  container_name: eventq_redis
  ports:
    - "6379:6379"
