rabbitmq:
  image: gonkulatorlabs/rabbitmq
  container_name: rabbitmq

testrunner:
  image: 522104923602.dkr.ecr.eu-west-1.amazonaws.com/sageone/sinatra:1.4.7-ruby-2.3.1-alpine-3.4
  container_name: gem_test_runner
  command: bash -c "./scripts/container_loop.sh"
  links:
    - rabbitmq
    - redis
  volumes:
    - ./container_loop.sh:/scripts/container_loop.sh
    - ../:/gem_src

redis:
  image: redis:alpine
  container_name: eventq_redis
  ports:
    - "6379:6379"
